# Linguagem sendo utilizada
language: python

# Versões do Python
python:
  - "3.7"
  - "3.8"
  - "pypy"

# Instalar as dependências
install:
#   - pip install .
   - pip install -r requirements.txt

# Script para rodar os tests
#script:
#  - run test.py test

#after_script:
#notifications:
  #recipients:
    #- davisegundo626@gmail.com
